### ISSUE TITLE
Batch job submission through QEMIST

### ISSUE THREAD

**Issue by elloyd-1qbit** [sandbox-quantum/Tangelo#105]
It would be great to submit batch jobs to AWS Braket through QEMIST when running hardware experiments. Their API supports this. The feature would also need to keep track of the job ids for each circuit so we can call the results from QEMIST. 

The input could be dictionary input like:  {"job_title": {num_shots : circuit}...}
Which returns : {"job_title": job_id}

**Comment by ValentinS4t1qbit** [comment]
We put this aside for a while, we are taking care of it this month.
I will make a `BraketConnection` and support batch submission, fully available to users to use with their own accounts if they want to.

Later this month, we will make sure QEMIST Cloud uses that `BraketConnection` to enable QEMIST Cloud users to leverage it using their credits.

**Comment by AlexandreF-1qbit** [comment]
While browsing the braket python package, I came across this function that could be useful for batch submission: https://github.com/aws/amazon-braket-sdk-python/blob/105433edb22ad2ccb50afbb72fd74ccb8d8d63b9/src/braket/aws/aws_device.py#L181-L265
